-- Baseline schema for JantaBank (matches the schema originally generated by Hibernate).
-- On an existing (already-populated) database this migration is skipped because Flyway
-- baselines at version 1; on a fresh database it recreates the full schema.

CREATE TABLE IF NOT EXISTS roles (
  id   BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS users (
  id        BIGINT NOT NULL AUTO_INCREMENT,
  aadhaarno VARCHAR(255) NOT NULL,
  address   VARCHAR(255) NOT NULL,
  email     VARCHAR(255) NOT NULL,
  mobile    VARCHAR(255) NOT NULL,
  name      VARCHAR(255) DEFAULT NULL,
  panno     VARCHAR(255) NOT NULL,
  password  VARCHAR(255) NOT NULL,
  status    BIGINT NOT NULL,
  username  VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_email (email),
  UNIQUE KEY uk_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS accounts (
  id                BIGINT NOT NULL AUTO_INCREMENT,
  accountholdername VARCHAR(255) NOT NULL,
  accountnumber     VARCHAR(255) NOT NULL,
  accounttype       VARCHAR(255) NOT NULL,
  address           VARCHAR(255) NOT NULL,
  balance           DOUBLE NOT NULL,
  branchid          VARCHAR(255) NOT NULL,
  contactnumber     VARCHAR(255) NOT NULL,
  emailaddress      VARCHAR(255) NOT NULL,
  ifsccode          VARCHAR(255) NOT NULL,
  nominee           VARCHAR(255) NOT NULL,
  opendate          DATETIME(6) NOT NULL,
  status            BIGINT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS beneficiaries (
  id                       BIGINT NOT NULL AUTO_INCREMENT,
  amountlimit              DOUBLE NOT NULL,
  beneficiaryaccountifsc   VARCHAR(255) NOT NULL,
  beneficiaryaccountname   VARCHAR(255) NOT NULL,
  beneficiaryaccountnumber VARCHAR(255) NOT NULL,
  status                   BIGINT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS transactions (
  id              BIGINT NOT NULL AUTO_INCREMENT,
  amount          DOUBLE NOT NULL,
  fromaccount     VARCHAR(255) NOT NULL,
  status          BIGINT NOT NULL,
  toaccount       VARCHAR(255) NOT NULL,
  transactiondate DATETIME(6) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS users_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  KEY fk_users_roles_role (role_id),
  CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS accounts_users (
  account_id BIGINT NOT NULL,
  user_id    BIGINT NOT NULL,
  PRIMARY KEY (account_id, user_id),
  KEY fk_accounts_users_user (user_id),
  CONSTRAINT fk_accounts_users_user    FOREIGN KEY (user_id)    REFERENCES users (id),
  CONSTRAINT fk_accounts_users_account FOREIGN KEY (account_id) REFERENCES accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS beneficiaries_accounts (
  beneficiary_id BIGINT NOT NULL,
  account_id     BIGINT NOT NULL,
  PRIMARY KEY (beneficiary_id, account_id),
  KEY fk_ben_accounts_account (account_id),
  CONSTRAINT fk_ben_accounts_account     FOREIGN KEY (account_id)     REFERENCES accounts (id),
  CONSTRAINT fk_ben_accounts_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
